// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/project/notif-project/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// BrandService is an autogenerated mock type for the BrandService type
type BrandService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, request
func (_m *BrandService) Create(ctx context.Context, request model.CreateBrandRequest) (int, *model.BaseResponse) {
	ret := _m.Called(ctx, request)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateBrandRequest) int); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 *model.BaseResponse
	if rf, ok := ret.Get(1).(func(context.Context, model.CreateBrandRequest) *model.BaseResponse); ok {
		r1 = rf(ctx, request)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model.BaseResponse)
		}
	}

	return r0, r1
}
