// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	model "github.com/richardsahvic/jamtangan/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// BrandRepository is an autogenerated mock type for the BrandRepository type
type BrandRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: brand
func (_m *BrandRepository) Create(brand string) (int64, error) {
	ret := _m.Called(brand)

	var r0 int64
	if rf, ok := ret.Get(0).(func(string) int64); ok {
		r0 = rf(brand)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(brand)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *BrandRepository) GetByID(id int64) (*model.Brand, error) {
	ret := _m.Called(id)

	var r0 *model.Brand
	if rf, ok := ret.Get(0).(func(int64) *model.Brand); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Brand)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
