// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	model "github.com/richardsahvic/jamtangan/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// TransactionRepository is an autogenerated mock type for the TransactionRepository type
type TransactionRepository struct {
	mock.Mock
}

// GetDetail provides a mock function with given fields: orderID
func (_m *TransactionRepository) GetDetail(orderID string) ([]*model.Transaction, error) {
	ret := _m.Called(orderID)

	var r0 []*model.Transaction
	if rf, ok := ret.Get(0).(func(string) []*model.Transaction); ok {
		r0 = rf(orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertList provides a mock function with given fields: order
func (_m *TransactionRepository) InsertList(order []model.Transaction) error {
	ret := _m.Called(order)

	var r0 error
	if rf, ok := ret.Get(0).(func([]model.Transaction) error); ok {
		r0 = rf(order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
